[package]
name = "queries-core"
version = "0.5.0-SNAPSHOT"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>", "Kevin Lefevre <kevin.lefevre@snips.ai>"]
repository = "https://github.com/snipsco/snips-queries-rust/"
description = "Rust implementation of the Queries SDK"
build = "build.rs"

[dependencies]
queries-utils = { path = "../queries-utils" }
queries-preprocessor = { path = "../queries-preprocessor" }
error-chain = { version = "0.10", default-features = false }
itertools = "0.6"
fst = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ndarray = "0.9"
regex = "0.2"
lazy_static = "0.2"
protobuf = "1.2"
rayon = "0.6"
tensorflow = "0.3"
csv = "0.15"
maplit = "0.1"
yolo = "*"
zip = { version = "0.2", default-features = false }

[dev-dependencies]
bencher = "0.1"

[build-dependencies]
glob = "0.2"

[[bench]]
name = "intent_classif"
harness = false

[[bench]]
name = "tokens_classif"
harness = false

[[bench]]
name = "intent_parser"
harness = false
