[package]
name = "queries-core"
version = "0.1.0"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>", "Kevin Lefevre <kevin.lefevre@snips.ai>"]
repository = "https://github.com/snipsco/snips-queries-rust/"
description = "Rust implementation of the Queries SDK"

[dependencies]
error-chain = { version = "0.9", default-features=false }
itertools = "0.5"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
ndarray = "0.7"
unicode-normalization = "0.1"
regex = "0.1"
lazy_static = "0.2"
protobuf = "1.2"
rayon = "0.6"
tensorflow = "0.2"
rulinalg = "0.4"
bencher = "0.1"

[[bench]]
name = "preprocess"
harness = false

[[bench]]
name = "intent_classif"
harness = false

[[bench]]
name = "tokens_classif"
harness = false

[[bench]]
name = "intent_parser"
harness = false
