[package]
name = "queries-core"
version = "0.5.0-SNAPSHOT"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>", "Kevin Lefevre <kevin.lefevre@snips.ai>"]
repository = "https://github.com/snipsco/snips-queries-rust/"
description = "Rust implementation of the Queries SDK"
build = "build.rs"

[dependencies]
error-chain = { version = "0.10", default-features=false }
itertools = "0.5"
fst = "0.1"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
ndarray = "0.9"
unicode-normalization = "0.1"
regex = "0.1"
lazy_static = "0.2"
protobuf = "1.2"
rayon = "0.6"
tensorflow = "0.3"
bencher = "0.1"
csv = "0.15.0"
yolo = "*"
zip = { version = "0.2", default-features = false }
rustling-ontology = { git = "ssh://git@github.com/snipsco/rustling-ontology.git", branch = "develop" }

[build-dependencies]
glob = "0.2"

[[bench]]
name = "preprocess"
harness = false

[[bench]]
name = "intent_classif"
harness = false

[[bench]]
name = "tokens_classif"
harness = false

[[bench]]
name = "intent_parser"
harness = false
