[package]
name = "snips-nlu-python-ffi"
version = "0.54.0"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]

[lib]
name = "snips_nlu_python_ffi"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
snips-nlu-ffi = { git = "https://github.com/snipsco/snips-nlu-rs", tag = "0.55.1" }
