[package]
name = "queries-embed"
version = "0.5.0-SNAPSHOT"
authors = ["Kevin LefeÌ€vre <kevin.lefevre@snips.ai>", "Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[dependencies]
queries-core = { path = "../queries-core" }
error-chain = { version = "0.10", default-features=false }
libc = "0.2"
serde_json = "0.9"
lazy_static = "0.2"

[lib]
crate-type = ["staticlib", "cdylib"]
